# 本番環境用のCertificate設定パッチ
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: webhook-tls
  namespace: webhook-system
spec:
  # 本番環境では長期間有効な証明書を使用
  duration: 8760h # 1年
  renewBefore: 2160h # 90日前に更新
  
  # 本番環境用のIssuerを使用
  issuerRef:
    name: webhook-letsencrypt-issuer
    kind: ClusterIssuer
    group: cert-manager.io
  
  # 本番環境のDNS名
  dnsNames:
    - webhook.production.example.com
    - k8s-deployment-hpa-validator.webhook-system.svc.cluster.local
  
  # より強固な秘密鍵設定
  privateKey:
    algorithm: RSA
    size: 4096
    rotationPolicy: Always