# Kustomize base configuration for k8s-deployment-hpa-validator
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: k8s-deployment-hpa-validator-base

# 共通リソース
resources:
  - deployment.yaml
  - service.yaml
  - rbac.yaml
  - configmap.yaml
  - validating-webhook-configuration.yaml
  - network-policy.yaml
  - pod-security-policy.yaml
  - certificate.yaml
  - cluster-issuer.yaml
  - issuer.yaml
  - pod-disruption-budget.yaml
  - servicemonitor.yaml
  - prometheusrule.yaml
  - grafana-dashboard.yaml

# 共通ラベル
labels:
  - pairs:
      app: k8s-deployment-hpa-validator
      component: webhook

# 共通アノテーション
commonAnnotations:
  app.kubernetes.io/name: k8s-deployment-hpa-validator
  app.kubernetes.io/component: webhook
  app.kubernetes.io/part-of: admission-controller

# 名前空間
namespace: webhook-system

# イメージ設定
images:
  - name: hpa-validator
    newTag: latest

# ConfigMapGeneratorは使用せず、configmap.yamlファイルを使用

# SecretはCert-Managerで自動生成されるため、ここでは定義しない