# Staging environment overlay
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: k8s-deployment-hpa-validator-staging

# ベース設定を参照
resources:
  - ../../base

# ステージング環境固有のラベル
labels:
  - pairs:
      environment: staging

# ステージング環境固有のアノテーション
commonAnnotations:
  app.kubernetes.io/version: staging

# 名前空間をステージング環境用に変更
namespace: webhook-system-staging

# イメージ設定（ステージング環境用）
images:
  - name: hpa-validator
    newTag: staging-latest

# ConfigMapの上書き（ステージング環境用設定）
configMapGenerator:
  - name: webhook-config
    behavior: replace
    literals:
      - webhook.port=8443
      - webhook.timeout=15s
      - webhook.failure-policy=Fail
      - log.level=info
      - log.format=json
      - metrics.enabled=true
      - metrics.port=8080
      - health.enabled=true
      - environment=staging
      - cluster.name=staging-cluster
      - validation.skip-namespaces=kube-system,kube-public,kube-node-lease,cert-manager,monitoring
      - validation.skip-labels=staging.io/skip-validation=true
    options:
      disableNameSuffixHash: true

# パッチファイル
patchesStrategicMerge:
  - deployment-patch.yaml
  - webhook-patch.yaml
  - pdb-patch.yaml

# JSON6902パッチ
patchesJson6902:
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: k8s-deployment-hpa-validator
    path: replica-patch.yaml