# ステージング環境用のPodDisruptionBudget
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: k8s-deployment-hpa-validator-pdb
spec:
  # ステージング環境では1つのPodが利用可能であれば十分（本番テスト用）
  minAvailable: 1
---
# ステージング環境用のHPA設定
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: k8s-deployment-hpa-validator-hpa
spec:
  minReplicas: 2
  maxReplicas: 5
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 75
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 85