apiVersion: v1
kind: ConfigMap
metadata:
  name: webhook-config
  namespace: webhook-system
  labels:
    app: k8s-deployment-hpa-validator
    component: config
data:
  # Webhook設定
  webhook.port: "8443"
  webhook.timeout: "30s"
  webhook.failure-policy: "Fail"
  
  # TLS設定
  webhook.tls-cert-file: "/etc/certs/tls.crt"
  webhook.tls-key-file: "/etc/certs/tls.key"
  
  # ログ設定
  log.level: "info"
  log.format: "json"
  
  # バリデーション設定
  validation.skip-namespaces: "monitoring,istio-system"
  validation.skip-labels: "production.io/skip-validation=true"
  
  # 監視設定
  metrics.enabled: "true"
  metrics.port: "8080"
  health.enabled: "true"
  
  # 環境情報
  environment: "production"
  cluster.name: "production-cluster"

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: webhook-config-staging
  namespace: webhook-system
  labels:
    app: k8s-deployment-hpa-validator
    component: config
    environment: staging
data:
  # Webhook設定
  webhook.port: "8443"
  webhook.timeout: "15s"
  webhook.failure-policy: "Fail"
  
  # TLS設定
  webhook.tls-cert-file: "/etc/certs/tls.crt"
  webhook.tls-key-file: "/etc/certs/tls.key"
  
  # ログ設定
  log.level: "info"
  log.format: "json"
  
  # バリデーション設定
  validation.skip-namespaces: "cert-manager,monitoring"
  validation.skip-labels: "staging.io/skip-validation=true"
  
  # 監視設定
  metrics.enabled: "true"
  metrics.port: "8080"
  health.enabled: "true"
  
  # 環境情報
  environment: "staging"
  cluster.name: "staging-cluster"

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: webhook-config-development
  namespace: webhook-system
  labels:
    app: k8s-deployment-hpa-validator
    component: config
    environment: development
data:
  # Webhook設定
  webhook.port: "8443"
  webhook.timeout: "10s"
  webhook.failure-policy: "Ignore"
  
  # TLS設定
  webhook.tls-cert-file: "/etc/certs/tls.crt"
  webhook.tls-key-file: "/etc/certs/tls.key"
  
  # ログ設定
  log.level: "debug"
  log.format: "text"
  
  # バリデーション設定
  validation.skip-namespaces: "local-path-storage"
  validation.skip-labels: "development.io/skip-validation=true"
  
  # 監視設定
  metrics.enabled: "true"
  metrics.port: "8080"
  health.enabled: "true"
  
  # 環境情報
  environment: "development"
  cluster.name: "development-cluster"