# TLS証明書用のSecret
# 実際の証明書データは scripts/generate-certs.sh で生成後に設定してください
apiVersion: v1
kind: Secret
metadata:
  name: k8s-deployment-hpa-validator-certs
  namespace: default
  labels:
    app: k8s-deployment-hpa-validator
    version: v1.0.0
    component: certs
type: kubernetes.io/tls
data:
  # 以下の値は scripts/generate-certs.sh 実行後に更新してください
  # tls.crt: <base64 encoded certificate>
  # tls.key: <base64 encoded private key>
  # ca.crt: <base64 encoded CA certificate>
  tls.crt: ""
  tls.key: ""
---
# CA証明書用の追加Secret（ValidatingAdmissionWebhookで使用）
apiVersion: v1
kind: Secret
metadata:
  name: k8s-deployment-hpa-validator-ca
  namespace: default
  labels:
    app: k8s-deployment-hpa-validator
    version: v1.0.0
    component: ca-cert
type: Opaque
data:
  # CA証明書（ValidatingAdmissionWebhookConfiguration用）
  # ca.crt: <base64 encoded CA certificate>
  ca.crt: ""