apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: k8s-deployment-hpa-validator
webhooks:
- name: deployment.validator.k8s-deployment-hpa-validator.io
  # 開発環境では失敗を無視
  failurePolicy: Ignore
  # タイムアウトを短縮
  timeoutSeconds: 5
  # 開発環境では全ての名前空間を対象とする
  namespaceSelector: {}
  # 開発環境用のオブジェクトセレクター
  objectSelector:
    matchExpressions:
    - key: development.io/skip-validation
      operator: NotIn
      values: ["true"]