apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: k8s-deployment-hpa-validator-dev
  namespace: argocd
  labels:
    app.kubernetes.io/name: k8s-deployment-hpa-validator
    app.kubernetes.io/component: webhook
    app.kubernetes.io/part-of: admission-control
    app.kubernetes.io/environment: development
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/your-org/k8s-deployment-hpa-validator.git
    targetRevision: HEAD
    path: manifests/overlays/development
  destination:
    server: https://kubernetes.default.svc
    namespace: webhook-system-dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
      - ApplyOutOfSyncOnly=true
    retry:
      limit: 3
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 1m
  revisionHistoryLimit: 5
  info:
    - name: 'Description'
      value: 'Kubernetes validating admission webhook for HPA/Deployment validation (Development)'
    - name: 'Environment'
      value: 'Development'
  ignoreDifferences:
    - group: apps
      kind: Deployment
      jsonPointers:
        - /spec/replicas